version = 0.1

[default]
[default.deploy.parameters]
stack_name = "sahayak-backend"
resolve_s3 = true
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = true

[default.build.parameters]
cached = true
parallel = true
